name: Debugging

on:
  push:
    branches:
      - joeyklee.devops-publish-workflow

jobs:
  debugging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Reconfigure git to use HTTP authentication
        run: >
          git config --global url."https://github.com/".insteadOf
          ssh://git@github.com/
      - uses: actions/setup-node@v2
        with:
          node-version: "12.x"
          registry-url: https://registry.npmjs.org/
      - uses: release-drafter/release-drafter@v5
        id: release_drafter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # bump the package version
      - run: echo "name ${{ steps.release_drafter.outputs.name }}"
      # - run: npm run update:packageVersion ${{ steps.release_drafter.outputs.name }}
      # update the readme
      # - run: npm run update:readme
      # install to update package-lock.json
      # - run: npm ci
      # - run: echo "passed npm ci"
      # run the build
      # - run: npm run build
      # - run: echo "passed build"
      # run the build
      # - run: npm publish ${{ steps.release_drafter.outputs.tag_name }}
