name: Debugging

on:
  push:
    branches:
      - joeyklee.devops-publish-workflow

jobs:
  debugging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: echo "passed npm ci"
      - run: npm run build
      - run: echo "passed build"
